### PR TITLE
Intro

### PR DESCRIPTION
**Pull request by gidden**
Ok, I left these changes for the end, because they might find opposition. Two changes are presented, both dealing with other simulator capabilities/origins.

The first is with respect to DANESS. It is now used in a commercial setting and is no longer developed by the labs. I noted as such.

The second is the CAFCA example. I opted to remove it, but would be happy if we would instead prefer another example (I couldn't come up with a great one off the top of my head...). To my knowledge, CAFCA does *not* have "excellent" economic capabilities. The only FCS you could say that of (to the best of my knowledge) is DANESS, post Argonne. I think the paragraph stands on its own without an example.

I'd be happy to discuss both suggestions.

### CODE REVIEW

**Comment by gidden** [comment]
Oh, also, I don't think ORION is an acronym..

**Comment by gidden** [comment]
and if it is, we should update the glossary.

**Comment by katyhuff** [comment]
- Regarding CAFCA: I wasn't trying to say it has economics at all. I just gave the economics example (thinking, actually, of NECOST, which isn't enough of a simulator to include here). I meant to express only that CAFCA disregards isotopics in favor of integral effects. My statement is just that it "is problem-oriented" in this way rather than "is great at economics in this way." Those sentences were meant to read more distinctly than it seems you've read them. I'd rather return the CAFCA example to its place and change the preceding sentence to be more clear. If you return the example to its place, I can try to make that preceding sentence more clear.

- Regarding ORION - it is not an acronym. 

> 
> ---------- Forwarded message ----------
> From: Katy Huff <katyhuff@gmail.com>
> Date: Wed, Feb 11, 2015 at 2:19 PM
> Subject: Re: Is ORION an acronym?
> To: "Worrall, Andrew" <worralla@ornl.gov>
>
> Fantastic. 
> Cyclus also stands for nothing. Acronyms are overrated.
> Thanks!!
>

**Comment by katyhuff** [comment]
ORION Is, however, usually referred to as "ORION". With only a few exceptions, most of their presentations are titled "ORION: and stuff" rather than "Orion: and stuff:.

**Comment by katyhuff** [comment]
(which is to say, nothing has to change about how we're treating ORION. I thought about it already)

**Comment by gidden** [comment]
Thanks for the replies @katyhuff. 

Regarding ORION, that makes sense. However, using it with the glossary package resulting in things like ORION (ORION). Maybe we could make it an `\Orion` or similar if you don't like this change?

Regarding CAFCA and economics, I simply point this out because, as a reader, this section *seems* to imply that certain FCS' have good economics and bad isotopics, and that CAFCA is one such simulator. My claim here is that it should be changed. I'm happy to have that section otherwise revised; I just suggested one approach. What do you think is best?

**Comment by katyhuff** [comment]
I'll check again, but I think I removed all instances of \gls{ORION} after
the email I quoted?

On Sun, Feb 22, 2015 at 5:52 PM, Matthew Gidden <notifications@github.com>
wrote:

> Thanks for the replies @katyhuff <https://github.com/katyhuff>.
>
> Regarding ORION, that makes sense. However, using it with the glossary
> package resulting in things like ORION (ORION). Maybe we could make it an
> \Orion or similar if you don't like this change?
>
> Regarding CAFCA and economics, I simply point this out because, as a
> reader, this section *seems* to imply that certain FCS' have good
> economics and bad isotopics, and that CAFCA is one such simulator. My claim
> here is that it should be changed. I'm happy to have that section otherwise
> revised; I just suggested one approach. What do you think is best?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/fundamentals-paper/pull/96#issuecomment-75479494>
> .
>



-- 
http://katyhuff.github.com

**Comment by katyhuff** [comment]
Regarding cafca : I'd rather return the CAFCA example to its place and
change the preceding sentence to be more clear. If you return the example
to its place, I can try to make that preceding sentence more clear.

On Sun, Feb 22, 2015 at 5:53 PM, Katy Huff <katyhuff@gmail.com> wrote:

> I'll check again, but I think I removed all instances of \gls{ORION} after
> the email I quoted?
>
> On Sun, Feb 22, 2015 at 5:52 PM, Matthew Gidden <notifications@github.com>
> wrote:
>
>> Thanks for the replies @katyhuff <https://github.com/katyhuff>.
>>
>> Regarding ORION, that makes sense. However, using it with the glossary
>> package resulting in things like ORION (ORION). Maybe we could make it an
>> \Orion or similar if you don't like this change?
>>
>> Regarding CAFCA and economics, I simply point this out because, as a
>> reader, this section *seems* to imply that certain FCS' have good
>> economics and bad isotopics, and that CAFCA is one such simulator. My claim
>> here is that it should be changed. I'm happy to have that section otherwise
>> revised; I just suggested one approach. What do you think is best?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cyclus/fundamentals-paper/pull/96#issuecomment-75479494>
>> .
>>
>
>
>
> --
> http://katyhuff.github.com
>



-- 
http://katyhuff.github.com

**Comment by katyhuff** [comment]
I see, I guess I missed one ORION. Thanks for catching it.

**Comment by gidden** [comment]
reverted cafca commit

**Comment by katyhuff** [comment]
Thanks for the PR! It looks great! I'll fix that intro bit asap.

**Pull request merged**
