### PR TITLE
final wrap ups

### PR DESCRIPTION
**Pull request by gidden**
**Not quite ready yet!**

- fix sim section typo

### CODE REVIEW

**Comment by gidden** [comment]
Lol, it's not done yet!

On Tue, Sep 8, 2015 at 5:48 PM, Katy Huff <notifications@github.com> wrote:

> Merged #136 <https://github.com/cyclus/fundamentals-paper/pull/136>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/fundamentals-paper/pull/136#event-403786339>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by katyhuff** [comment]
I'm confused. Why open an unready pr?

**Comment by gidden** [comment]
To warn others who might be editing the same items.

On Tue, Sep 8, 2015 at 5:56 PM, Katy Huff <notifications@github.com> wrote:

> I'm confused. Why open an unready pr?
>
> On Tue, Sep 8, 2015, 8:51 AM Matthew Gidden <notifications@github.com>
> wrote:
>
> > Lol, it's not done yet!
> >
> > On Tue, Sep 8, 2015 at 5:48 PM, Katy Huff <notifications@github.com>
> > wrote:
> >
> > > Merged #136 <https://github.com/cyclus/fundamentals-paper/pull/136>.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/cyclus/fundamentals-paper/pull/136#event-403786339
> >.
> > >
> >
> >
> >
> > --
> > Matthew Gidden, Ph.D.
> > Postdoctoral Associate, Nuclear Engineering
> > The University of Wisconsin -- Madison
> > Ph. 225.892.3192
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/cyclus/fundamentals-paper/pull/136#issuecomment-138606595
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/fundamentals-paper/pull/136#issuecomment-138608218>
> .
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gidden** [comment]
@gonuke has explicitly stated he will be editing soon, and I don't want
either of use to work on the same areas, so I'm trying to be as transparent
and explicit as possible.

On Tue, Sep 8, 2015 at 6:02 PM, Matthew Gidden <gidden@wisc.edu> wrote:

> To warn others who might be editing the same items.
>
> On Tue, Sep 8, 2015 at 5:56 PM, Katy Huff <notifications@github.com>
> wrote:
>
>> I'm confused. Why open an unready pr?
>>
>> On Tue, Sep 8, 2015, 8:51 AM Matthew Gidden <notifications@github.com>
>> wrote:
>>
>> > Lol, it's not done yet!
>> >
>> > On Tue, Sep 8, 2015 at 5:48 PM, Katy Huff <notifications@github.com>
>> > wrote:
>> >
>> > > Merged #136 <https://github.com/cyclus/fundamentals-paper/pull/136>.
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> https://github.com/cyclus/fundamentals-paper/pull/136#event-403786339>.
>> > >
>> >
>> >
>> >
>> > --
>> > Matthew Gidden, Ph.D.
>> > Postdoctoral Associate, Nuclear Engineering
>> > The University of Wisconsin -- Madison
>> > Ph. 225.892.3192
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/cyclus/fundamentals-paper/pull/136#issuecomment-138606595
>> >
>>
>> > .
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cyclus/fundamentals-paper/pull/136#issuecomment-138608218>
>> .
>>
>
>
>
> --
> Matthew Gidden, Ph.D.
> Postdoctoral Associate, Nuclear Engineering
> The University of Wisconsin -- Madison
> Ph. 225.892.3192
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by katyhuff** [comment]
ah gotcha. sorry.

On Tue, Sep 8, 2015 at 9:03 AM, Matthew Gidden <notifications@github.com>
wrote:

> @gonuke has explicitly stated he will be editing soon, and I don't want
> either of use to work on the same areas, so I'm trying to be as transparent
> and explicit as possible.
>
> On Tue, Sep 8, 2015 at 6:02 PM, Matthew Gidden <gidden@wisc.edu> wrote:
>
> > To warn others who might be editing the same items.
> >
> > On Tue, Sep 8, 2015 at 5:56 PM, Katy Huff <notifications@github.com>
> > wrote:
> >
> >> I'm confused. Why open an unready pr?
> >>
> >> On Tue, Sep 8, 2015, 8:51 AM Matthew Gidden <notifications@github.com>
> >> wrote:
> >>
> >> > Lol, it's not done yet!
> >> >
> >> > On Tue, Sep 8, 2015 at 5:48 PM, Katy Huff <notifications@github.com>
> >> > wrote:
> >> >
> >> > > Merged #136 <https://github.com/cyclus/fundamentals-paper/pull/136
> >.
> >> > >
> >> > > —
> >> > > Reply to this email directly or view it on GitHub
> >> > > <
> >> https://github.com/cyclus/fundamentals-paper/pull/136#event-403786339>.
> >> > >
> >> >
> >> >
> >> >
> >> > --
> >> > Matthew Gidden, Ph.D.
> >> > Postdoctoral Associate, Nuclear Engineering
> >> > The University of Wisconsin -- Madison
> >> > Ph. 225.892.3192
> >> >
> >> > —
> >> > Reply to this email directly or view it on GitHub
> >> > <
> >>
> https://github.com/cyclus/fundamentals-paper/pull/136#issuecomment-138606595
> >> >
> >>
> >> > .
> >> >
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/cyclus/fundamentals-paper/pull/136#issuecomment-138608218
> >
> >> .
> >>
> >
> >
> >
> > --
> > Matthew Gidden, Ph.D.
> > Postdoctoral Associate, Nuclear Engineering
> > The University of Wisconsin -- Madison
> > Ph. 225.892.3192
> >
>
>
>
> --
> Matthew Gidden, Ph.D.
> Postdoctoral Associate, Nuclear Engineering
> The University of Wisconsin -- Madison
> Ph. 225.892.3192
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/fundamentals-paper/pull/136#issuecomment-138612293>
> .
>



-- 
http://katyhuff.github.com

**Pull request merged**
